repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
      - id: terraform_checkov
        args:
          - --args=--compact
          - --args=--framework terraform
      - id: terraform_trivy
        args:
          - --args=--severity=HIGH,CRITICAL
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
